[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyDxQxQxQxQxQxQxQxQxQxQxQxQxQxQxQxQ"
  VITE_FIREBASE_AUTH_DOMAIN = "tee-green-spa-d13d8.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "tee-green-spa-d13d8"
  VITE_FIREBASE_STORAGE_BUCKET = "tee-green-spa-d13d8.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "123456789012"
  VITE_FIREBASE_APP_ID = "1:123456789012:web:1234567890123456789012"
  VITE_FIREBASE_MEASUREMENT_ID = "G-P7YGYXT0PX" 