[build]
  publish = "admin/appointments"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyBcMc0YY-WwRqVNbYaLc8087RohRe-1JVQ"
  VITE_FIREBASE_AUTH_DOMAIN = "tee-green-spa.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "tee-green-spa"
  VITE_FIREBASE_STORAGE_BUCKET = "tee-green-spa.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "626364577015"
  VITE_FIREBASE_APP_ID = "1:626364577015:web:d8f38c463437dc50a24ff2"
  VITE_FIREBASE_MEASUREMENT_ID = "G-P7YGYXT0PX" 